name: auto-git-push

on:
  workflow_dispatch:

jobs:
  auto-git-push:
    runs-on: ubuntu-20.04

    steps:
    - name: 准备工作
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
#        sudo apt -qq update
#        sudo apt -qq upgrade -y
        
    - name: 克隆仓库
      working-directory: /workdir
      run: |
        git clone https://github.com/pys078/github-actions-playground.git playground
        ln -sf /workdir/playground $GITHUB_WORKSPACE/playground
        
    - name: 创建一个文件
      run: |
        cd playground
        echo "Hello World\!">test.txt
      
    - name: commit
      run: |
        cd playground
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Github Actions 自动操作" -a
        
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
