name: auto-git-push

on:
  workflow_dispatch:

jobs:
  auto-git-push:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      
    - name: 准备工作
      run: |
        echo $PWD
#        sudo apt -qq update
#        sudo apt -qq upgrade -y
        
    - name: 创建一个文件
      run: |
        echo "Hello World\!">test.txt
      
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Github Actions 自动操作" -a
        
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_KEY }}
